services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .//lostos_game/backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/lostos_game
      FRONTEND_URL: http://localhost:5173
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./lostos_game/frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongo_data: